@startuml
... New key/translation ...
"Translation Service" <-- "Developer" : Pushes new key:translation
"Translation Service" <--> "PoEditor": Github Webbhooks calling PoEdit sync Webbhooks
...
... Client requests ...
"Client" --> "Translation Service" : GET /<namespace>/<locale>/
"Translation Service" --> "Client" : Actual JSON

"Client" --> "Translation Service" : GET /<namespace>/<locale>/<env>/
"Translation Service" --> "Client" : JSON for env (Stage, Prod)
...
... Sync with poEditor via api ...
"Translation Service" <-- "PoEditor": GET actual JSON every 10min
"Translation Service" <-- "PoEditor": GET actual JSON on translator request
...
@enduml